name: Crypto Actions
run-name: Crypto Actions
on: 
  pull_request:
    branches:
    - main
    paths:
    - src/*
    - .github/workflows/*
  push:
    branches:
    - main
    - dev
    paths:
    - src/*
    - .github/workflows/*

jobs:
  Build_Ubuntu-2204_Docker-GCC:
    strategy:
      matrix:
        gcc-version: [
          12.2.0, 12.1.0, 
          11.3.0, 11.2.0, 11.1.0, 
          10.4.0, 10.3.0, 10.2.0, 10.1.0, 
          9.5.0, 9.4.0, 9.3.0, 9.2.0, 9.1.0, 
          8.5.0, ]
    name: Build Ubuntu-22.04 Docker-GCC:${{ matrix.gcc-version }}
    runs-on: ubuntu-22.04
    container:
      image: gcc:${{ matrix.gcc-version }}
    outputs:
      output1: ${{ steps.Build.outputs.test }}
    steps:
    - uses: actions/checkout@v3.1.0
      id: Build
    - name: Build
      run: |
        make init
        make
        make init && time make
        make init && \time -v make

