name: Crypto Actions
run-name: Crypto Actions
on: 
  pull_request:
    branches:
        - main
  push:
    branches:
        - main
        - dev

jobs:
  Run:
    name: Run
    runs-on: ubuntu-22.04
    steps:
      - uses: ./.github/workflows/Build.yml
      - name: SHA-1 Test
        run: dist/crypto abc
