name: Crypto Actions
run-name: Crypto Actions
on: 
  pull_request:
    branches:
        - main
  push:
    branches:
        - main
        - dev

jobs:
  Run:
    name: Run
    uses: ./.github/workflows/Build.yml
    steps:
      - name: SHA-1 Test
        run: dist/crypto abc